apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: myfirstapp
  labels:
    cloud.googleapis.com/location: $REGION
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: myimage
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NAME
          value: MSBC
        resources:
          limits:
            memory: 512Mi
            cpu: 1000m
  traffic:
  - percent: 100
    latestRevision: true